// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpj85ZkPrnrFyEidgCYpOC8CoziwmdIVw',
    appId: '1:20839637148:web:2bebe7aa9a2cf8533b0d59',
    messagingSenderId: '20839637148',
    projectId: 'doctor-application-4a3c6',
    authDomain: 'doctor-application-4a3c6.firebaseapp.com',
    storageBucket: 'doctor-application-4a3c6.appspot.com',
    measurementId: 'G-1VYPCMH3YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8cqPrlAuDGWk6qN5SPdFFHHqRqPtFAE',
    appId: '1:20839637148:android:17a0a219a592246f3b0d59',
    messagingSenderId: '20839637148',
    projectId: 'doctor-application-4a3c6',
    storageBucket: 'doctor-application-4a3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnytr_7sJ9h8sSW8gTxVacgfePnvK3jW8',
    appId: '1:20839637148:ios:1b9eab2c010388913b0d59',
    messagingSenderId: '20839637148',
    projectId: 'doctor-application-4a3c6',
    storageBucket: 'doctor-application-4a3c6.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnytr_7sJ9h8sSW8gTxVacgfePnvK3jW8',
    appId: '1:20839637148:ios:1b9eab2c010388913b0d59',
    messagingSenderId: '20839637148',
    projectId: 'doctor-application-4a3c6',
    storageBucket: 'doctor-application-4a3c6.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );
}
